'use strict'

/**
 * Class for storing warning details.
 * @module fs-transform:warning
 * @author Ryan Sandor Richards
 */
module.exports = class Warning {
  /**
   * Constructs a new warning instance with that was generated by the given rule
   * and contains the given message.
   * @param {object} rule Rule that generated the warning.
   * @param {string} message Message for the warning.
   */
  constructor (rule, message) {
    this.rule = rule
    this.message = message
  }
}
